#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Log a message to the Vercel build console
echo "--- Installing build dependencies for ReportLab ---"

# Use yum to install the C compiler (gcc) and Python development headers.
# These are required to compile the C extensions in the ReportLab package.
yum install -y gcc python3-devel

# Log another message
echo "--- Collecting Django Static Files ---"

# Run the collectstatic command.
python3.12 manage.py collectstatic --noinput --clear
