# Generated by Django 5.2.4 on 2025-07-05 11:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='Default University', max_length=255)),
                ('pvc_name', models.CharField(default='Default PVC', max_length=255)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BOAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_college_name', models.CharField(max_length=255)),
                ('mou_signed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('aedp_programme', models.CharField(max_length=255)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_college_name', models.CharField(max_length=255)),
                ('aedp_programme', models.CharField(max_length=255)),
                ('curriculum_type', models.TextField()),
                ('same_aedp_continued', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('existing_degree_converted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('faculty_department', models.CharField(max_length=255)),
                ('duration', models.CharField(choices=[('3-Year UG', '3-Year UG'), ('4-Year UG', '4-Year UG')], max_length=20)),
                ('apprenticeship_integration', models.TextField()),
                ('student_intake', models.PositiveIntegerField()),
                ('industry_partners', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
                ('sector_name', models.CharField(max_length=255)),
                ('mou_signed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('type_of_engagement', models.CharField(max_length=255)),
                ('contact_person', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('aedp_programme', models.CharField(max_length=255)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodal_officer_orientation', models.CharField(blank=True, max_length=255)),
                ('faculty_workshops', models.PositiveIntegerField(default=0)),
                ('industry_workshops', models.PositiveIntegerField(default=0)),
                ('district_outreach_programs', models.PositiveIntegerField(default=0)),
                ('parent_orientation', models.PositiveIntegerField(default=0)),
                ('autonomous_colleges_onboarded', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('component', models.CharField(choices=[('Syllabus Preparation', 'Syllabus Preparation'), ('Credit Allocation', 'Credit Allocation'), ('Board of Deans Approval', 'Board of Deans Approval'), ('Academic Council Approval', 'Academic Council Approval')], max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=20)),
                ('timeline', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_name', models.CharField(max_length=255)),
                ('sector_name', models.CharField(max_length=255)),
                ('mou_signed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('aedp_programme', models.CharField(max_length=255)),
                ('type_of_engagement', models.TextField()),
                ('contact_person', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssc_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_finalization', models.CharField(blank=True, max_length=255)),
                ('mou_execution', models.CharField(blank=True, max_length=255)),
                ('internal_approvals', models.CharField(blank=True, max_length=255)),
                ('faculty_orientation', models.CharField(blank=True, max_length=255)),
                ('admission_campaign_launch', models.CharField(blank=True, max_length=255)),
                ('student_enrollment_begin', models.CharField(blank=True, max_length=255)),
                ('program_commencement', models.CharField(blank=True, max_length=255)),
                ('monthly_progress_reporting', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
