# Generated by Django 5.2.4 on 2025-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='component',
        ),
        migrations.RemoveField(
            model_name='program',
            name='status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='timeline',
        ),
        migrations.AddField(
            model_name='boat',
            name='no_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boat',
            name='stipend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='student_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='stipend_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='student_commitment',
            field=models.PositiveIntegerField(default=0, verbose_name='Student commitment for apprenticeship (no. of students)'),
        ),
        migrations.AddField(
            model_name='industry',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_council_approval',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20, verbose_name='Academic Council Approval'),
        ),
        migrations.AddField(
            model_name='program',
            name='board_of_deans_approval',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20, verbose_name='Board of Deans Approval'),
        ),
        migrations.AddField(
            model_name='program',
            name='credit_allocation',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='syllabus_preparation',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='ssc',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssc',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='aedp_programme',
            field=models.CharField(max_length=255, verbose_name='Title of AEDP Programme'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='campus_college_name',
            field=models.CharField(max_length=255, verbose_name='University Campus / College Name'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='MoU Signed with BOAT (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='apprenticeship_integration',
            field=models.TextField(verbose_name='Mention the semesters in which apprenticeship is integrated and the total credits allocated.'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='duration',
            field=models.CharField(choices=[('3-Year UG', '3-Year UG'), ('4-Year UG', '4-Year UG')], max_length=20, verbose_name='AEDP Duration (3-Year UG / 4-Year UG)'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='existing_degree_converted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Existing Degree Programme Converted to AEDP? (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='industry_partners',
            field=models.TextField(verbose_name='Industry Partner(s) Details'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='same_aedp_continued',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Same AEDP (with CRISP & SSC) Continued? (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='student_intake',
            field=models.PositiveIntegerField(verbose_name='Probable Student Intake'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='aedp_programme',
            field=models.CharField(max_length=255, verbose_name='Title of AEDP Programme'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='contact_person',
            field=models.TextField(verbose_name='Contact Person Name, Designation & Contact Details'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='MoU Signed Status (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='type_of_engagement',
            field=models.CharField(max_length=255, verbose_name='Type of Engagement (Curriculum, Apprenticeship, Assessment, Stipend etc.)'),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='aedp_programme',
            field=models.CharField(max_length=255, verbose_name='Title of AEDP Programme'),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='contact_person',
            field=models.TextField(verbose_name='Contact Person, Designation & Contact Details'),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='MoU Signed Status (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='type_of_engagement',
            field=models.TextField(verbose_name='Type of Engagement of SSC Contact MoU (Curriculum Preparation Assessment, Visiting Faculty, Stipend provision etc.)'),
        ),
    ]
