# Generated by Django 5.2.4 on 2025-07-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_program_component_remove_program_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='timeline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Timeline (Target Completion date, If pending)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='credit_allocation',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20, verbose_name='Credit Allocation'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='syllabus_preparation',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20, verbose_name='Syllabus Preparation'),
        ),
    ]
