# Generated by Django 5.2.4 on 2025-07-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_program_timeline_alter_program_credit_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='aedp_programme',
            field=models.CharField(max_length=255, verbose_name='Title of AEDP Programme'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='type_of_engagement',
            field=models.CharField(max_length=255, verbose_name='Type of Engagement (Curriculum, Apprenticeship, Assessment, Training etc.)'),
        ),
    ]
