# Generated by Django 5.2.4 on 2025-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_campus_aedp_programme_and_more'),
    ]

    operations = [

    ]
