# Generated by Django 5.2.4 on 2025-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_campus_aedp_programme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='sector_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sector Name'),
        ),
    ]
