# Generated by Django 5.2.4 on 2025-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_location_industry_location_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='location',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='aishe_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='district',
            field=models.CharField(default='Ahmednagar', max_length=64),
        ),
        migrations.AddField(
            model_name='campus',
            name='sector_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sector Name'),
        ),
        migrations.AddField(
            model_name='industry',
            name='curriculum_consulted_to_industry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Curriculum Consulted to Industry (Yes/No)'),
        ),
        migrations.AddField(
            model_name='industry',
            name='location_head',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='other_locations',
            field=models.TextField(blank=True, null=True, verbose_name='Other Locations'),
        ),
    ]
