# Generated by Django 5.2.4 on 2025-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_campus_sector_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_name',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='aishe_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='district',
            field=models.CharField(default='Ahmednagar', max_length=64),
        ),
        migrations.AddField(
            model_name='industry',
            name='curriculum_consulted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3, verbose_name='Curriculum Consulted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='location_head',
            field=models.CharField(default='', max_length=255, verbose_name='Head Office Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='location_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Location'),
        ),
        migrations.AddField(
            model_name='program',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='program_documents/', verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='program',
            name='program',
            field=models.CharField(choices=[('B.Sc', 'B.Sc'), ('BBA', 'BBA'), ('B.Com', 'B.Com'), ('B.E', 'B.E'), ('B.Tech', 'B.Tech'), ('M.Sc', 'M.Sc'), ('M.Tech', 'M.Tech'), ('M.Com', 'M.Com'), ('MBA', 'MBA'), ('Other', 'Other')], default='', max_length=10, verbose_name='Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(default='', max_length=255, verbose_name='Specialization/Branch'),
            preserve_default=False,
        ),
    ]
