# Generated by Django 5.2.4 on 2025-07-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_industry_location_basicinfo_aishe_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['location_head', 'other_locations', 'curriculum_consulted_to_industry']},
        ),
    ]
