# Generated by Django 5.2.4 on 2025-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_program_curriculum_file_program_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='degree',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(choices=[('B.Com', 'B.Com'), ('B.A.', 'B.A.'), ('B.Sc.', 'B.Sc.'), ('B.M.S.', 'B.M.S.'), ('B.Tech', 'B.Tech'), ('B.B.A.', 'B.B.A.'), ('M.Com.', 'M.Com.'), ('M.A.', 'M.A.'), ('M.Sc.', 'M.Sc.'), ('M.B.A', 'M.B.A'), ('M.Tech', 'M.Tech'), ('Others', 'Others')], max_length=20, verbose_name='Program Name'),
        ),
    ]
