# Generated by Django 5.2.4 on 2025-07-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_program_degree_alter_program_program_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name': 'Basic Information', 'verbose_name_plural': 'Basic Information'},
        ),
        migrations.AlterModelOptions(
            name='boat',
            options={'verbose_name': 'Board of Apprenticeship Training (BOAT)', 'verbose_name_plural': 'Board of Apprenticeship Training (BOAT)'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus Details', 'verbose_name_plural': 'Campus Details'},
        ),
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['curriculum_consulted_to_industry', 'location_head', 'other_locations'], 'verbose_name': 'Industry Engagement', 'verbose_name_plural': 'Industry Engagements'},
        ),
        migrations.AlterModelOptions(
            name='outreach',
            options={'verbose_name': 'Outreach Activity', 'verbose_name_plural': 'Outreach Activities'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program Details', 'verbose_name_plural': 'Program Details'},
        ),
        migrations.AlterModelOptions(
            name='ssc',
            options={'verbose_name': 'Sector Skill Council (SSC)', 'verbose_name_plural': 'Sector Skill Councils (SSC)'},
        ),
        migrations.AlterModelOptions(
            name='timelines',
            options={'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
        migrations.AddField(
            model_name='program',
            name='ability_enhancement_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='apprenticeship_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='major_minor_multidisciplinary_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='num_curriculum_ticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='skill_enhancement_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='value_added_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='academic_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='aishe_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='pvc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='university_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boat',
            name='aedp_programme',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boat',
            name='campus_college_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='boat',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='boat',
            name='no_of_students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='stipend',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campus',
            name='aedp_programme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='apprenticeship_integration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='duration',
            field=models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years')], max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='existing_degree_converted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='industry_partners',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='same_aedp_continued',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='sector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='student_enrolled',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='student_intake',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='industry',
            name='aedp_programme',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='contact_person',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='curriculum_consulted_to_industry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='industry',
            name='other_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='stipend_range',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='student_commitment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='type_of_engagement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='autonomous_colleges_onboarded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='district_outreach_programs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='faculty_workshops',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='industry_workshops',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='nodal_officer_orientation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='parent_orientation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_council_approval',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='board_of_deans_approval',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='credit_allocation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='curriculum_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculum_files/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='other_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(choices=[('B.Voc', 'B.Voc'), ('M.Voc', 'M.Voc'), ('D.Voc', 'D.Voc'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='syllabus_preparation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='aedp_programme',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='contact_person',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='mou_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='type_of_engagement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='admission_campaign_launch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='curriculum_finalization',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='faculty_orientation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='internal_approvals',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='monthly_progress_reporting',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='mou_execution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='program_commencement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='student_enrollment_begin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
